[workspace]
resolver = "3"
members = [
    "apps/desktop/src-tauri",
    "crates/auth",
    "crates/contracts",
    "crates/domain",
    "crates/loaders",
    "crates/installer",
    "crates/minecraft",
    "crates/modpack-client",
    "crates/modpack-api-contracts",
    "crates/platform",
    "crates/process",
    "crates/storage",
    "tools/xtask",
    "services/modpack-api",
]
default-members = [
    "apps/desktop/src-tauri",
    "crates/auth",
    "crates/contracts",
    "crates/domain",
    "crates/loaders",
    "crates/installer",
    "crates/minecraft",
    "crates/modpack-client",
    "crates/modpack-api-contracts",
    "crates/platform",
    "crates/process",
    "crates/storage",
    "tools/xtask",
    "services/modpack-api",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
publish = false

[workspace.dependencies]
base64 = "=0.22.1"
anyhow = "=1.0.104"
async-trait = "=0.1.92"
axum = "=0.8.9"
directories = "=6.0.0"
futures-util = "=0.3.32"
keyring = "=4.2.0"
proptest = "=1.11.0"
regex = "=1.13.1"
reqwest = { version = "=0.13.5", default-features = false, features = ["json", "rustls"] }
schemars = { version = "=1.2.2", features = ["uuid1"] }
secrecy = "=0.10.3"
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = "=1.0.151"
sqlx = { version = "=0.9.0", default-features = false, features = [
    "macros",
    "migrate",
    "runtime-tokio",
    "sqlite",
    "time",
    "uuid",
] }
sha1 = "=0.11.0"
sha2 = "=0.11.0"
shlex = "=2.0.1"
tempfile = "=3.27.0"
thiserror = "=2.0.20"
sysinfo = { version = "=0.39.6", default-features = false, features = ["system"] }
time = { version = "=0.3.51", features = [
    "formatting",
    "parsing",
    "serde",
    "serde-well-known",
] }
tokio = { version = "=1.53.1", features = [
    "fs",
    "io-util",
    "macros",
    "net",
    "process",
    "rt-multi-thread",
    "sync",
    "time",
] }
uuid = { version = "=1.26.1", features = ["serde", "v4"] }
url = "=2.5.8"
zip = { version = "=8.3.0", default-features = false, features = ["deflate-flate2-zlib-rs"] }
tauri = "=2.11.4"
tauri-build = "=2.6.3"
tauri-plugin-dialog = "=2.7.3"
moka = { version = "=0.12.16", features = ["sync"] }
percent-encoding = "=2.3.2"
tower = "=0.5.3"
tower-http = { version = "=0.7.1", features = ["compression-gzip", "cors", "request-id", "trace"] }
tracing = "=0.1.44"
tracing-subscriber = { version = "=0.3.23", features = ["env-filter", "fmt", "json"] }

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
dbg_macro = "deny"
expect_used = "deny"
todo = "deny"
unimplemented = "deny"
unwrap_used = "deny"
