[package]
name = "slate-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[build-dependencies]
tauri-build.workspace = true

[dependencies]
slate-contracts = { path = "../../../crates/contracts" }
slate-domain = { path = "../../../crates/domain" }
slate-installer = { path = "../../../crates/installer" }
slate-loaders = { path = "../../../crates/loaders" }
slate-minecraft = { path = "../../../crates/minecraft" }
slate-platform = { path = "../../../crates/platform" }
slate-process = { path = "../../../crates/process" }
slate-storage = { path = "../../../crates/storage" }
serde_json.workspace = true
tauri.workspace = true
uuid.workspace = true

[lints]
workspace = true
