[package]
name = "slate-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[build-dependencies]
tauri-build.workspace = true

[dependencies]
base64.workspace = true
futures-util.workspace = true
hickory-resolver.workspace = true
slate-auth = { path = "../../../crates/auth" }
slate-contracts = { path = "../../../crates/contracts" }
slate-domain = { path = "../../../crates/domain" }
slate-installer = { path = "../../../crates/installer" }
slate-loaders = { path = "../../../crates/loaders" }
slate-minecraft = { path = "../../../crates/minecraft" }
slate-modpack-api-contracts = { path = "../../../crates/modpack-api-contracts" }
slate-modpack-client = { path = "../../../crates/modpack-client" }
slate-platform = { path = "../../../crates/platform" }
slate-process = { path = "../../../crates/process" }
slate-storage = { path = "../../../crates/storage" }
serde.workspace = true
serde_json.workspace = true
tauri.workspace = true
tauri-plugin-opener = "=2.5.2"
tauri-plugin-dialog.workspace = true
time.workspace = true
tokio.workspace = true
thiserror.workspace = true
sysinfo.workspace = true
tempfile.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
uuid.workspace = true
zip.workspace = true
tauri-plugin-updater = "=2.11.0"

[lints]
workspace = true
