use crate::response::{ApiError, CacheControl, RequestContext, success};
use crate::state::AppState;
use crate::support_reports::{MAX_SUPPORT_REPORT_BYTES, SupportReportStoreError};
use axum::Router;
use axum::body::Bytes;
use axum::extract::rejection::BytesRejection;
use axum::extract::{DefaultBodyLimit, Extension, State};
use axum::http::header::CONTENT_TYPE;
use axum::http::{HeaderMap, StatusCode};
use axum::response::Response;
use axum::routing::post;
use slate_modpack_api_contracts::{ApiErrorCode, SupportReportReceipt};
use uuid::Uuid;

const REPORT_ID_HEADER: &str = "x-slate-report-id";

pub fn routes() -> Router<AppState> {
    Router::new().route(
        "/support/reports",
        post(upload).layer(DefaultBodyLimit::max(MAX_SUPPORT_REPORT_BYTES)),
    )
}

async fn upload(
    State(state): State<AppState>,
    Extension(context): Extension<RequestContext>,
    headers: HeaderMap,
    body: Result<Bytes, BytesRejection>,
) -> Result<Response, ApiError> {
    let body = body.map_err(|_| {
        ApiError::new(
            &context,
            StatusCode::PAYLOAD_TOO_LARGE,
            ApiErrorCode::InvalidRequest,
            "The support report is larger than 20 MiB.",
            false,
        )
    })?;
    validate_archive(&context, &headers, &body)?;
    let report_id = headers
        .get(REPORT_ID_HEADER)
        .and_then(|value| value.to_str().ok())
        .and_then(|value| Uuid::parse_str(value).ok())
        .ok_or_else(|| {
            ApiError::invalid_request(&context, "The support report identifier is invalid.")
                .with_field("reportId", "Use the identifier generated by slate.")
        })?;
    let bytes = u64::try_from(body.len()).unwrap_or(u64::MAX);
    state
        .support_reports
        .put(report_id, body)
        .await
        .map_err(|error| storage_error(&context, error))?;
    tracing::info!(report_id = %report_id, bytes, "support report stored");
    Ok(success(
        &context,
        SupportReportReceipt { report_id, bytes },
        CacheControl::NoStore,
    ))
}

fn validate_archive(
    context: &RequestContext,
    headers: &HeaderMap,
    body: &Bytes,
) -> Result<(), ApiError> {
    let content_type = headers
        .get(CONTENT_TYPE)
        .and_then(|value| value.to_str().ok())
        .unwrap_or_default();
    if content_type != "application/zip" {
        return Err(ApiError::invalid_request(
            context,
            "The support report must be a ZIP archive.",
        )
        .with_field("contentType", "Use application/zip."));
    }
    if body.len() < 4 || !matches!(&body[..4], b"PK\x03\x04" | b"PK\x05\x06") {
        return Err(ApiError::invalid_request(
            context,
            "The support report archive is invalid.",
        ));
    }
    Ok(())
}

fn storage_error(context: &RequestContext, error: SupportReportStoreError) -> ApiError {
    tracing::error!(error = %error, "support report storage failed");
    ApiError::new(
        context,
        StatusCode::SERVICE_UNAVAILABLE,
        ApiErrorCode::SupportReportUnavailable,
        "Support report delivery is temporarily unavailable.",
        true,
    )
}

#[cfg(test)]
mod tests {
    use super::validate_archive;
    use crate::response::RequestContext;
    use axum::body::Bytes;
    use axum::http::header::CONTENT_TYPE;
    use axum::http::{HeaderMap, HeaderValue};

    #[test]
    fn accepts_zip_archives_and_rejects_other_content() {
        let context = RequestContext::for_test();
        let mut headers = HeaderMap::new();
        headers.insert(CONTENT_TYPE, HeaderValue::from_static("application/zip"));
        assert!(
            validate_archive(&context, &headers, &Bytes::from_static(b"PK\x03\x04data")).is_ok()
        );
        assert!(validate_archive(&context, &headers, &Bytes::from_static(b"not a zip")).is_err());
    }
}
